### ISSUE TITLE
Cronjob update resets productattributes with a default value

### ISSUE THREAD

**Issue by mjschenk** [pricemotion/magento2#1]
After each cronjob, all productattributes with a default value reset and lose their initial value. This happens to all products, as there is no way to exclude products from being updated. The module had to be completely removed to verify this was the cause of the dataloss, because the cronjob keeps running after the module is disabled. Looking at the code I found something dubious:

https://github.com/pricemotion/magento2/blob/6a22240791f18e66fbdb95f76cb60ab360d50840/Cron/Update.php#L137

On line 137 of update.php a save() is performed for the whole product, without loading its content with a load(). This usually leads to dataloss. It's also more efficient to just save the affected attributes with something like:

`$this->productResourceModel->saveAttribute($product, $affected_attribute);`

Our catalog has alot of these attibutes with a default value, including all yes/no attributes. Every attribute for every product is wiped. As it took a couple of weeks to notice the dataloss, we've updated our catalog several time during the issue. Therefore I can't just revert back to a backup and have restore all lost data with imports.

**Comment by apeschar** [comment]
@mjschenk, thanks for reporting this issue and investigating the cause.

I'm currently investigating the issue and trying to reproduce it locally. As far as I have seen so far, the `save()` action should not actually overwrite attributes that haven't been loaded or changed in that product. But I have found two relevant issues specifically addressing default values.

* https://github.com/magento/magento2/issues/12881
* https://github.com/magento/magento2/issues/8897

These issues seem to describe a situation where an attribute has "Use Default Value" checked in a store view.  Saving the product then causes "Use Default Value" to be unchecked.  The attribute value itself should not actually get overwritten.

Can you confirm whether the effective attribute values were actually changed (eg, Yes was changed to No), or whether only the "Use Default Value" setting was changed, causing the default attribute value to be copied to the store view?  In the latter case the effective value would stay the same, it would just not be tied to the default value anymore.

**Comment by mjschenk** [comment]
It even happens to global attributes, so there's not even an option to select whether it should "Use Default Value". The actual value is changed.

**Comment by apeschar** [comment]
I cannot reproduce this problem with 2.3.4 or 2.3.6.  There must be something specific about your Magento version or another module that loads the default attribute values.  The Magento save code checks whether attributes are part of the entity (the product), and since they have been loaded with only specific attributes, those default attributes should not be there.

https://github.com/magento/magento2/blob/3bcbd95c723065d18d63b01d8f7bfb9b1cb9fe0d/app/code/Magento/Eav/Model/ResourceModel/UpdateHandler.php#L130-L137

But it doesn't matter.  I've updated the module in version 1.1.5 to not use the `save` method to update products.  You can update to this version from GitHub, or wait until it is approved by Magento.

Thanks for your quick reply.

**Comment by mjschenk** [comment]
I'm on version 2.4.1, and had the same issue on 2.4.0. We've updated to [v1.1.5](https://github.com/pricemotion/magento2/tree/v1.1.5), thanks. Will post results here!

**Comment by mjschenk** [comment]
The problem seems to be solved with [v1.1.5](https://github.com/pricemotion/magento2/tree/v1.1.5), attributes with  default value keep their set value.
